version: 2
jobs:
  dependencies:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - /root/.cache/Cypress
          key: dependencies-v1-{{ checksum "yarn.lock" }}
  test:cypress:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn cy:cache
      - run: yarn cy:ci
      - run: yarn cy:report
  eslint:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn lint:es
  build:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-dependencies-v1-{{ checksum "yarn.lock" }}
            - build-dependencies-v1-
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn cross-env NODE_ENV=production TINIFY_API_KEY_CI=$TINIFY_API_KEY webpack
      - save_cache:
          paths:
            - node_modules
            - .cache
          key: build-dependencies-v1-{{ checksum "yarn.lock" }}
      - store_artifacts:
          path: build
          destination: build
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(node -p "require('./package.json').version")
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - test:cypress:
          requires:
            - dependencies
      - eslint:
          requires:
            - dependencies
      - build:
          filters:
            branches:
              only: master
          requires:
            - test:cypress
            - eslint
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
